/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thanhtd.view;

import com.thanhtd.controller.DbController;
import com.thanhtd.model.User;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author trduy
 */
public class AddInformationFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddInformationFrame
     */
    public AddInformationFrame() {
        initComponents();
        setupApp();
    }

    private void setupApp() {
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addUsernameTxt = new javax.swing.JTextField();
        addPasswordTxt = new javax.swing.JPasswordField();
        addRepassTxt = new javax.swing.JPasswordField();
        addUrlTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addNoteTxt = new javax.swing.JTextArea();
        addCloseBtn = new javax.swing.JButton();
        addSaveBtn = new javax.swing.JButton();
        addGenPass = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setTitle("Add Information");

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jLabel3.setText("Retype password");

        jLabel4.setText("URL");

        jLabel5.setText("Information");

        addNoteTxt.setColumns(20);
        addNoteTxt.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        addNoteTxt.setRows(5);
        jScrollPane1.setViewportView(addNoteTxt);

        addCloseBtn.setText("Close");
        addCloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCloseBtnActionPerformed(evt);
            }
        });

        addSaveBtn.setText("Save");
        addSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSaveBtnActionPerformed(evt);
            }
        });

        addGenPass.setText("Generate password");
        addGenPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addGenPassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addGenPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addGenPassMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addUsernameTxt)
                                    .addComponent(addPasswordTxt)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addUrlTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addGenPass)
                            .addComponent(addRepassTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addSaveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addCloseBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(addUsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRepassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addGenPass)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUrlTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCloseBtn)
                    .addComponent(addSaveBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addGenPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addGenPassMouseEntered
        addGenPass.setForeground(java.awt.Color.blue);
    }//GEN-LAST:event_addGenPassMouseEntered

    private void addGenPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addGenPassMouseExited
        addGenPass.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_addGenPassMouseExited

    private void addCloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCloseBtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_addCloseBtnActionPerformed

    private void addGenPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addGenPassMouseClicked
        if (SwingUtilities.isLeftMouseButton(evt)) {
            NewPassGeneratorFrame newpass = new NewPassGeneratorFrame();
            newpass.getContentPane();
        }
    }//GEN-LAST:event_addGenPassMouseClicked

    private void addSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSaveBtnActionPerformed
        if (addUsernameTxt.getText().trim().compareTo("") == 0) {
            JOptionPane.showMessageDialog(this, "Please provide Username.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (String.valueOf(addPasswordTxt.getPassword()).compareTo("") == 0) {
                JOptionPane.showMessageDialog(this, "Please provide Password.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if (String.valueOf(addRepassTxt.getPassword()).compareTo("") == 0) {
                    JOptionPane.showMessageDialog(this, "Please provide Password.", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (addUrlTxt.getText().trim().compareTo("") == 0) {
                        JOptionPane.showMessageDialog(this, "Please provide Url.", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        if (String.valueOf(addPasswordTxt.getPassword()).compareTo(String.valueOf(addRepassTxt.getPassword())) == 0) {
                            boolean check = false;
                            for (int i = 0; i < Main.dlm.size(); i++) {
                                User temp = (User) Main.dlm.getElementAt(i);
                                if (temp.getUsername().toUpperCase().compareTo(addUsernameTxt.getText().toUpperCase()) == 0
                                        && temp.getUrl().toLowerCase().compareTo(addUrlTxt.getText().toLowerCase()) == 0) {
                                    check = true;
                                }
                            }
                            if (check) {
                                JOptionPane.showMessageDialog(this, "User " + addUsernameTxt.getText() + " existed \nin Url: " + addUrlTxt.getText()
                                        + "\nPlease try again.", "Error", JOptionPane.ERROR_MESSAGE);
                            } else {
                                String tempUsername = addUsernameTxt.getText();
                                String tempUrl = addUrlTxt.getText();
                                String tempNote = (addNoteTxt.getText().compareTo("") == 0) ? "" : addNoteTxt.getText();
                                String tempPass = String.valueOf(addPasswordTxt.getPassword());

                                User temp = new User(tempUsername, tempPass, tempUrl, tempNote);
                                Main.dlm.addElement(temp);
                                DbController.InsertInfoToDB(temp);
                                setVisible(false);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Password not match", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_addSaveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
        //    public static void main(String args[]) {
    //        /* Set the Nimbus look and feel */
    //        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    //        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
    //         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
    //         */
    //        try {
    //            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
    //                if ("Nimbus".equals(info.getName())) {
    //                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
    //                    break;
    //                }
    //            }
    //        } catch (ClassNotFoundException ex) {
    //            java.util.logging.Logger.getLogger(AddInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        } catch (InstantiationException ex) {
    //            java.util.logging.Logger.getLogger(AddInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        } catch (IllegalAccessException ex) {
    //            java.util.logging.Logger.getLogger(AddInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    //            java.util.logging.Logger.getLogger(AddInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    //        }
    //        //</editor-fold>
    //
    //        /* Create and display the form */
    //        java.awt.EventQueue.invokeLater(new Runnable() {
    //            public void run() {
    //                new AddInformationFrame().setVisible(true);
    //            }
    //        });
    //    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCloseBtn;
    private javax.swing.JLabel addGenPass;
    private javax.swing.JTextArea addNoteTxt;
    private javax.swing.JPasswordField addPasswordTxt;
    private javax.swing.JPasswordField addRepassTxt;
    private javax.swing.JButton addSaveBtn;
    private javax.swing.JTextField addUrlTxt;
    private javax.swing.JTextField addUsernameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
