/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thanhtd.view;

import com.thanhtd.controller.DbController;
import com.thanhtd.model.User;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import javax.swing.JOptionPane;
import org.apache.commons.codec.digest.DigestUtils;

/**
 *
 * @author Thanh Tran
 */
public class ChangeMasterPassFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChangeMasterPassFrame
     */
    public ChangeMasterPassFrame() {
        initComponents();
        setupApp();

        changempCancelBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                setVisible(false);
            }
        });

        changempOkBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (!(Arrays.toString(changempReNewPassTxt.getPassword()).isEmpty() || Arrays.toString(changempNewPassTxt.getPassword()).isEmpty() || Arrays.toString(changempCurrentPassTxt.getPassword()).isEmpty())) {
                    if (DigestUtils.md5Hex(String.valueOf(changempCurrentPassTxt.getPassword())).compareTo(Main.AES_PASSWORD_KEY) == 0) {
                        if (String.valueOf(changempReNewPassTxt.getPassword()).compareTo(String.valueOf(changempNewPassTxt.getPassword())) == 0) {
                            DbController.ClearAllData();
                            //Set new pass for MASTERPASSWORD
                            User temp = new User();
                            temp.setUsername("MASTERPASSWORD");
                            //temp.setPassword(String.valueOf(jPasswordField1.getPassword()));
                            temp.setPassword(DigestUtils.md5Hex(String.valueOf(changempReNewPassTxt.getPassword())));
                            temp.setUrl("MASTERPASSWORD");
                            temp.setNote("MASTERPASSWORD");

                            //Main.AES_PASSWORD = String.valueOf(jPasswordField1.getPassword());
                            Main.AES_PASSWORD_KEY = DigestUtils.md5Hex(String.valueOf(changempReNewPassTxt.getPassword()));

                            DbController.InsertInfoToDB(temp, true);

                            //Write all data to DB with new AES_KEY
                            for (int i = 0; i < Main.dlm.getSize(); i++) {
                                User tempInsert = new User();
                                User tempOld = (User) Main.dlm.getElementAt(i);

                                tempInsert.setUsername(tempOld.getUsername());
                                tempInsert.setPassword(tempOld.getPassword());
                                tempInsert.setUrl(tempOld.getUrl());
                                tempInsert.setNote(tempOld.getNote());
                                DbController.InsertInfoToDB(tempInsert);
                            }
                            JOptionPane.showMessageDialog(null, "Master password changed.");
                            setVisible(false);
                        } else {
                            JOptionPane.showMessageDialog(null, "Password is not match.", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Current Master Password is wrong.", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Please fill all data, or click Cancel.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    private void setupApp() {
        setVisible(true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        changempReNewPassTxt = new javax.swing.JPasswordField();
        changempNewPassTxt = new javax.swing.JPasswordField();
        changempCurrentPassTxt = new javax.swing.JPasswordField();
        changempCancelBtn = new javax.swing.JButton();
        changempOkBtn = new javax.swing.JButton();

        setTitle("Change Master Password");
        setResizable(false);

        jLabel1.setText("Current Master Password");

        jLabel2.setText("New Master Password");

        jLabel3.setText("Retype new Master Password");

        changempCancelBtn.setText("Cancel");

        changempOkBtn.setText("OK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changempCurrentPassTxt)
                            .addComponent(changempNewPassTxt)
                            .addComponent(changempReNewPassTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(changempOkBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(changempCancelBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(changempCurrentPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(changempNewPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(changempReNewPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changempCancelBtn)
                    .addComponent(changempOkBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChangeMasterPassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChangeMasterPassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChangeMasterPassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChangeMasterPassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ChangeMasterPassFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changempCancelBtn;
    private javax.swing.JPasswordField changempCurrentPassTxt;
    private javax.swing.JPasswordField changempNewPassTxt;
    private javax.swing.JButton changempOkBtn;
    private javax.swing.JPasswordField changempReNewPassTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
