/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thanhtd.view;

import com.thanhtd.controller.DbController;
import com.thanhtd.controller.EncryptDecrypt;
import com.thanhtd.model.User;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Thanh Tran
 */
public class EditInformationFrame extends javax.swing.JFrame {

    /**
     * Creates new form ShowInformationFrame
     */
    User item;
    EncryptDecrypt encryptDecrypt;
    
    //Test on 06Nov
    public EditInformationFrame() {
        initComponents();
        setupApp();
    }

    public void setData(User i) {
        this.item = i;
    }
    //end of test
    
    public void executeFrame() {
        editUsernameTxt.setText(item.getUsername());
        editPassTxt.setText("Hidden password!");
        editRepassTxt.setText("Hidden password!");
        editUrlTxt.setText(item.getUrl());
        editNoteTxt.setText(item.getNote());
    }

    public EditInformationFrame(User i) {
        initComponents();
        setupApp();

        this.item = i;

        editUsernameTxt.setText(item.getUsername());
        editPassTxt.setText("Hidden password!");
        editRepassTxt.setText("Hidden password!");
        editUrlTxt.setText(item.getUrl());
        editNoteTxt.setText(item.getNote());
    }

    private void setupApp() {
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        editUsernameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        editNoteTxt = new javax.swing.JTextArea();
        editPassTxt = new javax.swing.JTextField();
        editUrlTxt = new javax.swing.JTextField();
        editCloseBtn = new javax.swing.JButton();
        editShowPass = new javax.swing.JLabel();
        editSaveBtn = new javax.swing.JButton();
        editGenPass = new javax.swing.JLabel();
        editRepassTxt = new javax.swing.JTextField();
        editDeleteBtn = new javax.swing.JButton();

        setTitle("Edit Information");
        setResizable(false);

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jLabel3.setText("URL");

        jLabel4.setText("Information");

        editNoteTxt.setColumns(20);
        editNoteTxt.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        editNoteTxt.setRows(5);
        editNoteTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editNoteTxtFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(editNoteTxt);

        editPassTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editPassTxtFocusGained(evt);
            }
        });

        editUrlTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editUrlTxtFocusGained(evt);
            }
        });

        editCloseBtn.setText("Close");
        editCloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCloseBtnActionPerformed(evt);
            }
        });

        editShowPass.setText("Show password");
        editShowPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editShowPassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editShowPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editShowPassMouseExited(evt);
            }
        });

        editSaveBtn.setText("Save");
        editSaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSaveBtnActionPerformed(evt);
            }
        });

        editGenPass.setText("Generate password");
        editGenPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editGenPassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editGenPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editGenPassMouseExited(evt);
            }
        });

        editRepassTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                editRepassTxtFocusGained(evt);
            }
        });

        editDeleteBtn.setText("Delete");
        editDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDeleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editUrlTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(editDeleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editSaveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editCloseBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(28, 28, 28)
                                    .addComponent(editUsernameTxt))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(30, 30, 30)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(editShowPass)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(editGenPass))
                                        .addComponent(editPassTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(editRepassTxt, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(editUsernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(editPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editRepassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editGenPass)
                    .addComponent(editShowPass, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editUrlTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editCloseBtn)
                    .addComponent(editSaveBtn)
                    .addComponent(editDeleteBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editShowPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editShowPassMouseEntered
        editShowPass.setForeground(java.awt.Color.blue);
    }//GEN-LAST:event_editShowPassMouseEntered

    private void editShowPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editShowPassMouseExited
        editShowPass.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_editShowPassMouseExited

    private void editCloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCloseBtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_editCloseBtnActionPerformed

    private void editSaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSaveBtnActionPerformed
        if (item.getPassword().compareTo(editPassTxt.getText()) != 0) {
            if (editPassTxt.getText().compareTo(editRepassTxt.getText()) == 0) {
                User temp = new User();
                temp.setUsername(editUsernameTxt.getText());
                temp.setPassword(editPassTxt.getText());
                temp.setUrl(editUrlTxt.getText());
                temp.setNote(editNoteTxt.getText());

                DbController.UpdateInfoToDB(item, temp);
                Main.dlm.setElementAt(temp, Main.selectedItem);
                setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "New password is not match.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            setVisible(false);
        }
    }//GEN-LAST:event_editSaveBtnActionPerformed

    private void editGenPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editGenPassMouseEntered
        editGenPass.setForeground(Color.blue);
    }//GEN-LAST:event_editGenPassMouseEntered

    private void editGenPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editGenPassMouseExited
        editGenPass.setForeground(Color.black);
    }//GEN-LAST:event_editGenPassMouseExited

    private void editGenPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editGenPassMouseClicked
        NewPassGeneratorFrame newpass = new NewPassGeneratorFrame();
        newpass.getContentPane();
    }//GEN-LAST:event_editGenPassMouseClicked

    private void editPassTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editPassTxtFocusGained
        editPassTxt.selectAll();
    }//GEN-LAST:event_editPassTxtFocusGained

    private void editRepassTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editRepassTxtFocusGained
        editRepassTxt.selectAll();
    }//GEN-LAST:event_editRepassTxtFocusGained

    private void editUrlTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editUrlTxtFocusGained
        editUrlTxt.selectAll();
    }//GEN-LAST:event_editUrlTxtFocusGained

    private void editNoteTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_editNoteTxtFocusGained
        editNoteTxt.selectAll();
    }//GEN-LAST:event_editNoteTxtFocusGained

    private void editShowPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editShowPassMouseClicked
        if (editShowPass.getText().compareTo("Show password") == 0) {
            editPassTxt.setText(item.getPassword());
            editRepassTxt.setText(item.getPassword());
            editShowPass.setText("Hide password");
        } else {
            editPassTxt.setText("Hidden password!");
            editRepassTxt.setText("Hidden password!");
            editShowPass.setText("Show password");
        }
    }//GEN-LAST:event_editShowPassMouseClicked

    private void editDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDeleteBtnActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Would you like to delete this User Information?", "Warning", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            Main.dlm.remove(Main.selectedItem);
            DbController.RemoveInfoFromDB(item);
            setVisible(false);
        }
    }//GEN-LAST:event_editDeleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EditInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EditInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EditInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EditInformationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EditInformationFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editCloseBtn;
    private javax.swing.JButton editDeleteBtn;
    private javax.swing.JLabel editGenPass;
    private javax.swing.JTextArea editNoteTxt;
    private javax.swing.JTextField editPassTxt;
    private javax.swing.JTextField editRepassTxt;
    private javax.swing.JButton editSaveBtn;
    private javax.swing.JLabel editShowPass;
    private javax.swing.JTextField editUrlTxt;
    private javax.swing.JTextField editUsernameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
