/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thanhtd.view;

import com.thanhtd.controller.DbController;
import com.thanhtd.model.User;
import java.awt.Color;
import javax.swing.DefaultListModel;

/**
 *
 * @author Thanh Tran
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public static DefaultListModel dlm = null;
    DefaultListModel backup = null;

    public static int selectedItem;

    final public static String AES_MASTER_PASSWORD_KEY = "I_AM_HARDWELL_UnitedWeAre7111988";
    public static String AES_PASSWORD_KEY = "";

    public Main() {
        initComponents();
        setupApp();

//        DbController.ConnectToDB();
//
//        User masterUser = DbController.GetMasterpassFromDB();
//        if (masterUser == null) {
//            MasterPasswordFrame masterPass = new MasterPasswordFrame(this);
//            masterPass.getContentPane();
//        } else {
//            AES_PASSWORD_KEY = masterUser.getPassword();
//            LoginFrame login = new LoginFrame(this);
//            login.getContentPane();
//
//            DbController.ReadFromDB(dlm);
//            jList1.setModel(dlm);
//        }
    }

    private void setupApp() {
        //Set windows location to Center
        setLocationRelativeTo(null);

        dlm = new DefaultListModel();
        backup = new DefaultListModel();

        //Set the default position of cursor in JtextField
        mainSearchTxt.setCaretPosition(0);

        //encryptDecrypt = new EncryptDecrypt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSearchTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainJlist = new javax.swing.JList();
        mainAddBtn = new javax.swing.JButton();
        mainChangeMp = new javax.swing.JLabel();
        mainAbout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Password Management");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        mainSearchTxt.setText("Search");
        mainSearchTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mainSearchTxtFocusLost(evt);
            }
        });
        mainSearchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mainSearchTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mainSearchTxtKeyReleased(evt);
            }
        });

        mainJlist.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        mainJlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainJlistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mainJlist);

        mainAddBtn.setText("Add");
        mainAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainAddBtnActionPerformed(evt);
            }
        });

        mainChangeMp.setText("Change master password");
        mainChangeMp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainChangeMpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainChangeMpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mainChangeMpMouseExited(evt);
            }
        });

        mainAbout.setText("About");
        mainAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainAboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mainAboutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(mainAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainChangeMp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainAbout))
                    .addComponent(mainSearchTxt))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainSearchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainAddBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainChangeMp)
                    .addComponent(mainAbout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainJlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainJlistMouseClicked
        if (evt.getClickCount() == 2) {
            selectedItem = mainJlist.getSelectedIndex();
            User temp = (User) mainJlist.getSelectedValue();

            //ok
//            EditInformationFrame edit = new EditInformationFrame(temp);
//            edit.getContentPane();
            //test 06Nov15
            EditInformationFrame edit = new EditInformationFrame();
            edit.setData(temp);
            edit.executeFrame();
        }
    }//GEN-LAST:event_mainJlistMouseClicked

    private void mainAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainAddBtnActionPerformed
        AddInformationFrame addInfo = new AddInformationFrame();
        addInfo.getContentPane();
    }//GEN-LAST:event_mainAddBtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        mainJlist.setModel(dlm);
    }//GEN-LAST:event_formWindowActivated

    private void mainSearchTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainSearchTxtKeyPressed
        if (mainSearchTxt.getText().compareTo("Search") == 0) {
            mainSearchTxt.setText("");
        }
    }//GEN-LAST:event_mainSearchTxtKeyPressed

    private void mainSearchTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainSearchTxtKeyReleased
        if (mainSearchTxt.getText().compareTo("") == 0) {
            if (mainJlist.getModel().getSize() > 0) {
                dlm = backup;
            }
            mainJlist.setModel(dlm);
        } else {
            DefaultListModel tempList = new DefaultListModel();
            for (int i = 0; i < dlm.getSize(); i++) {
                User tempUser = (User) dlm.getElementAt(i);
                if (tempUser.getUsername().toUpperCase().contains(mainSearchTxt.getText().toUpperCase())
                        || tempUser.getUrl().toUpperCase().contains(mainSearchTxt.getText().toUpperCase())
                        || tempUser.getNote().toUpperCase().contains(mainSearchTxt.getText().toUpperCase())) {
                    tempList.addElement(tempUser);
                }
            }
            backup = dlm;
//            dlm = tempList;
            mainJlist.setModel(tempList);
        }
    }//GEN-LAST:event_mainSearchTxtKeyReleased

    private void mainSearchTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mainSearchTxtFocusLost
        if (mainSearchTxt.getText().compareTo("") == 0) {
            mainSearchTxt.setText("Search");
        }
    }//GEN-LAST:event_mainSearchTxtFocusLost

    private void mainChangeMpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainChangeMpMouseEntered
        mainChangeMp.setForeground(Color.blue);
    }//GEN-LAST:event_mainChangeMpMouseEntered

    private void mainChangeMpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainChangeMpMouseExited
        mainChangeMp.setForeground(Color.black);
    }//GEN-LAST:event_mainChangeMpMouseExited

    private void mainChangeMpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainChangeMpMouseClicked
        ChangeMasterPassFrame changeMP = new ChangeMasterPassFrame();
        changeMP.getContentPane();

//        MasterPasswordFrame masterpassword = new MasterPasswordFrame(this, dlm);
//        masterpassword.getContentPane();
//        jList1.setModel(dlm);
    }//GEN-LAST:event_mainChangeMpMouseClicked

    private void mainAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainAboutMouseEntered
        mainAbout.setForeground(Color.blue);
    }//GEN-LAST:event_mainAboutMouseEntered

    private void mainAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainAboutMouseExited
        mainAbout.setForeground(Color.black);
    }//GEN-LAST:event_mainAboutMouseExited

    private void mainAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainAboutMouseClicked
        AboutFrame aboutFrame = new AboutFrame();
        aboutFrame.getContentPane();
    }//GEN-LAST:event_mainAboutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>
        Main main = new Main();
        DbController.ConnectToDB();

        User masterUser = DbController.GetMasterpassFromDB();
        if (masterUser == null) {
            MasterPasswordFrame masterPass = new MasterPasswordFrame(main);
            masterPass.getContentPane();
        } else {
            AES_PASSWORD_KEY = masterUser.getPassword();
            LoginFrame login = new LoginFrame(main);
            login.getContentPane();

            DbController.ReadFromDB(dlm);
            main.mainJlist.setModel(dlm);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                main.setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mainAbout;
    private javax.swing.JButton mainAddBtn;
    private javax.swing.JLabel mainChangeMp;
    private javax.swing.JList mainJlist;
    private javax.swing.JTextField mainSearchTxt;
    // End of variables declaration//GEN-END:variables
}
